#spring配置
spring:
  #切面启用
  aop:
    proxy-target-class: true
    auto: true


  mail:
    host: smtp.126.com
    post: 25
    username: mail
    password: LBQJOVBCBXXXXXX
    default-encoding: UTF-8
    properties:
      mail:
        debug: true
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory

  datasource:
    url: jdbc:mysql://47.98.xxx.xx:3306/vhr?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456