server:
  port: 8089

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://47.98.175.65:3306/learn_test?useUnicode=true&characterEncoding=utf8
      username: lzy
      password: 123456